activities:
  entrypoint:
    output: output
    activityRoot: .
    environment: 
      path:
        - .
      pythonPath:
        - .
    action:
      command:
        - python 
        - -m 
        - robot 
        - -d 
        - output 
        - --logtitle 
        - Task log 
        - .
condaConfig: conda.yaml
